### PR TITLE
Giant Swarm update

### PR DESCRIPTION
**Pull request by teemow**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by teemow** [comment]
@Oshratn @tommyhobin @henninglange 

Imo we should:

 * Update our description
 * Check which repo to submit to become open source to meet their requirements
 * Check the category we are in

**Comment by Oshratn** [comment]
@teemow just stumbled upon this and I am missing context.

**Comment by teemow** [comment]
Afaik this was about listing us as open-source and not closed source. But my suggestion here of the kubernetes repository isn't a good idea. Our CAPI compatible aws-operator is a much more active project.

I quickly checked the landscape and can't find us at all anymore. So yes we should check this.

**Comment by tommyhobin** [comment]
> I quickly checked the landscape and can't find us at all anymore.

We're listed under the Card mode here: 
https://landscape.cncf.io/format=card-mode&organization=giant-swarm

If you look for us under the Landscape, we are listed under _Special_: https://landscape.cncf.io/organization=giant-swarm

It's so clustered in that thing, I think the only way people would find us (or anyone) would be to search...

**Comment by teemow** [comment]
Thanks @tommyhobin. Yes it looks we are in the right categories. Still we disappear if you select the open source licenses. Which basically not true. But fine with me to keep it like that. We don't have one simple downloadable open-source kubernetes distribution that we promote. So I can live with this.

**Pull request closed without merging**
